-- Create import_jobs table
create table import_jobs (
  -- Generated by Rust application code as UUIDv7.
  id uuid primary key,
  status text not null,
  input_path text not null,
  attempts integer not null,
  last_error text,
  -- Set by the Rust application clock boundary.
  created_at timestamptz not null,
  updated_at timestamptz not null
);
