import './index.css'
import React from 'react'
import ReactDOM from 'react-dom/client'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'

// routeTree.gen.ts is auto-generated by the TanStack Router Vite plugin.
// Run `npm run dev` or `npm run build` to (re)generate it.
import { routeTree } from './routeTree.gen'

// ---------------------------------------------------------------------------
// TanStack Query client
// TanStack Query is the single source of truth for all server state.
// ---------------------------------------------------------------------------
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      // Retry once on failure before surfacing an error state to the UI.
      retry: 1,
      // Consider data stale immediately so a background refetch fires on
      // window focus. This keeps the product list accurate across tabs.
      staleTime: 0,
    },
  },
})

// ---------------------------------------------------------------------------
// TanStack Router
// Owns URL and screen state exclusively. Components must NOT manage
// navigation via window.location or local state.
// ---------------------------------------------------------------------------
const router = createRouter({ routeTree })

// Augment the module so TypeScript can type-check <Link to="..." /> paths.
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

// ---------------------------------------------------------------------------
// Mount
// ---------------------------------------------------------------------------
const rootElement = document.getElementById('root')!

ReactDOM.createRoot(rootElement).render(
  <React.StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </React.StrictMode>,
)
